---
- pip: name={{ item }} state=present
  with_items:
    - python-memcached
    - sentry[postgres]
    - redis
    - hiredis
    - nydus
  notify: restart supervisor
- template: src=sentry.conf.j2 dest={{ config_file }}
  notify: restart supervisor

- command: sentry --config=/etc/sentry.conf.py upgrade --noinput

